
output:
  pdf_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Getting and Cleansing Data Project
### Author: Yuliya Grobman (kbzunder@gmail.com)

Additional information about the variables, data and transformations used in the course project for the Johns Hopkins Getting and Cleaning Data course.

### Source Data
## A Data and Description can be found here:
<http://archive.isc.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones}>

## Data Set Information

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 
Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

## Attribute Information

### For each record in the dataset it is provided:

* Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
* Triaxial Angular velocity from the gyroscope.
* A 561-feature vector with time and frequency domain variables.
* Its activity label.
* An identifier of the subject who carried out the experiment.

## Instructions:

* Megrge the training and the test sets to create one data set.
* Extract only the measurements on the mean and standart deviation for each measurement.
* Use descriptive activity names to name the activities in the data set
* Appropriately labels the data set with descriptive var nams.
* From the data set in previous step, create a second, independent tidy data set with the average of each variable for each activity and each subject.

## Implementation
* data downloaded into R and unziped
* usind rio package, data imported to R:
* created 2 data sets, TrainData and TestData
* for each data set, added two columns: SubjectNum and 
Activity
* Columns of each data set named according to features.txt
* two data sets (TrainData and TestData) were merged in one
named Merged, using rbind() command
* making a factor var from a column called Activ 
* selecting only vars including names std and mean, giving a new data frame name Selected_Merged
* renaming the columns of the new data frame, exlucing () rom var names
* creating an independent data set, called aggregated, which
inludes the average of each var for each activity and each
subject

